name: Certora

env:
  CI: true

on:
  pull_request:
    paths:
      - packages/**

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      base: ${{ steps.filter.outputs.base }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            base:
              - 'packages/base/**'

  prove-base:
    needs: changes
    if: ${{ needs.changes.outputs.base == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prove base
        uses: ./.github/actions/certora
        with:
          workspace: '@mimic-fi/v2-smart-vaults-base'
          certora-key: ${{ secrets.CERTORA_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
