name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Job failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Job cancelled
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Job cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
