name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Job failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with: { severity: error, details: Job failed!, webhookUrl: ${ { inputs.discord-webhook } } }
      - name: Job cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with: { severity: warn, details: Job cancelled!, webhookUrl: ${ { inputs.discord-webhook } } }

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Job failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with: { severity: error, details: Job failed!, webhookUrl: ${{ inputs.discord-webhook }} }
      - name: Job cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with: { severity: warn, details: Job cancelled!, webhookUrl: ${{ inputs.discord-webhook }} }

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Job failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with: { severity: error, details: Job failed!, webhookUrl: ${ { inputs.discord-webhook } } }
      - name: Job cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with: { severity: warn, details: Job cancelled!, webhookUrl: ${ { inputs.discord-webhook } } }
